// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bianca-about/Editorial.tsx": () => import("../components/mockups/bianca-about/Editorial.tsx"),
  "./components/mockups/bianca-about/Grid.tsx": () => import("../components/mockups/bianca-about/Grid.tsx"),
  "./components/mockups/bianca-about/Stacked.tsx": () => import("../components/mockups/bianca-about/Stacked.tsx")
};
